version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - patrick.zippenfenig
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: "*"
      - update-types: ["version-update:semver-patch"]
    commit-message:
      prefix: "fix: "
    groups:
      semantic:
        patterns:
          - "semantic-release"
          - "@semantic/*"
      svelte:
        patterns:
          - "@sveltejs/*"
          - "svelte-*"
          - "svelte"
          - "vite"
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "saas"
          - "typescript"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    commit-message:
      prefix: "fix: "
